version: '3.8'

services:
  app:
    # image: ardli/antrian-klinik:latest
    build:
      context: .
    container_name: laravel_app_prod
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./docker/php.ini:/usr/local/etc/php/php.ini
    networks:
      - laravel-network
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - APP_ENV=development
      - APP_DEBUG=true

  webserver:
    image: nginx:alpine
    container_name: laravel_webserver_prod
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./public:/var/www/html/public
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel-network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: laravel_db_prod
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - dbdata_prod:/var/lib/mysql
      - ./antrian.sql:/docker-entrypoint-initdb.d/antrian.sql
    networks:
      - laravel-network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  dbdata_prod:

networks:
  laravel-network:
    driver: bridge
