services:
  app:
    build:
      context: .
    container_name: antrian_app_prod
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./docker/php.ini:/usr/local/etc/php/php.ini
    networks:
      - antrian-network
      - net
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - APP_ENV=production
      - APP_DEBUG=false
    expose:
      - "9000"

  db:
    image: mysql:8.0
    container_name: laravel_db_prod
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - dbdata_prod:/var/lib/mysql
      - ./antrian.sql:/docker-entrypoint-initdb.d/antrian.sql
    networks:
      - antrian-network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  dbdata_prod:

networks:
  antrian-network:
    driver: bridge